steps:
- name: python:3.7
  id: INSTALL
  entrypoint: python3
  args:
  - '-m'
  - 'pip'
  - 'install'
  - '-t'
  - '.'
  - '-r'
  - 'functions/requirements.txt'
- name: python:3.7
  entrypoint: python3
  id: RUN-UNIT-TESTS
  args:
  - '-m'
  - 'nose2'
  - '-s'
  - 'functions'
  - '-c'
  - 'functions/nose2.cfg'
  waitFor:
  - INSTALL
- name: python:3.7
  entrypoint: python3
  id: RUN-COVERAGE-TESTS
  args:
  - '-c'
  - 'import sys; from pycobertura import Cobertura, TextReporter; cobertura = Cobertura("functions/coverage.xml"); tr = TextReporter(cobertura); coverage = tr.generate().split(" ")[-1].strip("%"); print("Coverage OK:",coverage + "% > 90%") if float(coverage) > 90 else sys.exit("Coverage is less than 90%")'
  waitFor:
  - RUN-UNIT-TESTS
- name: python:3.7
  entrypoint: python3
  id: RUN-LINTER-CHECK
  args:
  - '-m'
  - 'flake8'
  - '--ignore=E501'
  - 'functions/'
  waitFor:
  - INSTALL
- name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy"]
timeout: "1600s"
